### ISSUE TITLE
Model for improvements to affect units etc

### ISSUE THREAD

**Issue by minttu** [piesome/valta#5]

**Comment by minttu** [comment]
Super basic model implemented in bd62ea1bc06b917b51e18f94fa1747a357d1b58a.
Some more work is needed to make the improvements nicer to add

**Comment by jaakaappi** [comment]
Renamed improvements to effects

**Comment by jaakaappi** [comment]
Units have classes (think infantry, cavalry)

Units have combat modifiers that define a damage multiplier towards a unit class. Modifiers are stored in target(class)-modifier pairs. Targets are defined as strings, modifiers as numbers
